server:
  port: 18081

spring:
  application:
    name: service-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

dubbo:
  protocols:
    dubbo:
      name: dubbo
      port: 20811
    rest:
      name: rest
      port: 9090
      server: netty
  registry:
    address: spring-cloud://localhost