#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: false #是否将自身注册到eureka
#    fetchRegistry: false #是否抓取注册信息
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

server:
  port: 18082

spring:
  application:
    name: service-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

